[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log

[program:web_service]
command=python -u app.py
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/app/logs/web.log
stderr_logfile=/app/logs/web.log

[program:main_csv]
command=python -u main.py
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/app/logs/main.log
stderr_logfile=/app/logs/main.log

[program:api_has]
command=python -u hasSend.py
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/app/logs/has-send.log
stderr_logfile=/app/logs/has-send.log

[program:klhk_send]
command=python -u send.py
directory=/app/klhk
autostart=true
autorestart=true
stdout_logfile=/app/logs/send.log
stderr_logfile=/app/logs/send.log


[program:klhk_retry]
command=python -u retry.py
directory=/app/klhk
autostart=true
autorestart=true
stdout_logfile=/app/logs/retry.log
stderr_logfile=/app/logs/retry.log

[program:cleanup_logs]
command=python -u log_cleanup.py
directory=/app/backend
autostart=true
autorestart=true
stdout_logfile=/app/logs/cleanup.log
stderr_logfile=/app/logs/cleanup.log


