[supervisord]
nodaemon=true
logfile=/app/logs/supervisord.log
logfile_maxbytes=1MB
logfile_backups=1
pidfile=/tmp/supervisord.pid
childlogdir=/app/logs
user=root


[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700


[supervisorctl]
serverurl=unix:///tmp/supervisor.sock


[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface


[program:web_service]
command=python -u app.py
directory=/app/backend
autostart=true
autorestart=unexpected
startsecs=5
startretries=3
stopwaitsecs=20
stopasgroup=true
killasgroup=true
stdout_logfile=/app/logs/web.log
stdout_logfile_maxbytes=2MB
stdout_logfile_backups=1
stderr_logfile=/app/logs/web.log
stdout_events_enabled=false
stderr_events_enabled=false


[program:main_csv]
command=python -u main.py
directory=/app/backend
autostart=true
autorestart=unexpected
startsecs=5
startretries=3
stopwaitsecs=20
stopasgroup=true
killasgroup=true
stdout_logfile=/app/logs/main.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=1
stderr_logfile=/app/logs/main.log
stdout_events_enabled=false
stderr_events_enabled=false


[program:api_has]
command=python -u hasSend.py
directory=/app/backend
autostart=true
autorestart=unexpected
startsecs=5
startretries=3
stopwaitsecs=20
stopasgroup=true
killasgroup=true
stdout_logfile=/app/logs/has-send.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=1
stderr_logfile=/app/logs/has-send.log
stdout_events_enabled=false
stderr_events_enabled=false


[program:klhk_send]
command=python -u send.py
directory=/app/klhk
autostart=true
autorestart=unexpected
startsecs=5
startretries=3
stopwaitsecs=20
stopasgroup=true
killasgroup=true
stdout_logfile=/app/logs/send.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=1
stderr_logfile=/app/logs/send.log
stdout_events_enabled=false
stderr_events_enabled=false


[program:klhk_retry]
command=python -u retry.py
directory=/app/klhk
autostart=true
autorestart=unexpected
startsecs=5
startretries=3
stopwaitsecs=20
stopasgroup=true
killasgroup=true
stdout_logfile=/app/logs/retry.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=1
stderr_logfile=/app/logs/retry.log
stdout_events_enabled=false
stderr_events_enabled=false
